
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukmnjakkvtbaayqyntgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrbW5qYWtrdnRiYWF5cXludGdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NDY3MjYsImV4cCI6MjA1ODUyMjcyNn0.AFVUK7ZRXHckJtrvSJG-X07xxFuo4ZQUvXDjFyNDdh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
